---
# tasks file for agent_setup
- name: Setup Salt Agent
  ansible.builtin.include_tasks: "{{ salt_agent | default('minion') }}.yml"
- name: Accept salt keys of any new minions
  ansible.builtin.command: "salt-key -a {{ inventory_hostname }}"
  delegate_to: "{{ salt_master }}"
  when:
    - "(salt_agent | default('minion')) in ['minion']"