---
- name: Ensure the Salt Master is setup if in the play hosts
  ansible.builtin.include_tasks: "{{ salt_agent | default('minion') }}.yml"
  when:
    - "(salt_agent | default('minion')) in ['master']"
- name: Setup Salt Minions if in the minion list
  ansible.builtin.include_tasks: "{{ salt_agent | default('minion') }}.yml"
  when:
    - "(salt_agent | default('minion')) in ['minion']"  
- name: Accept salt keys of any new minions
  ansible.builtin.command: "salt-key -a {{ inventory_hostname }} -y"
  delegate_to: "{{ salt_master }}"
  become: true
  when:
    - "(salt_agent | default('minion')) in ['minion']"
