---
- name: Add the salt-master service to the firewall to permit incoming connections
  ansible.posix.firewalld:
    service: salt-master
    permanent: yes
    state: enabled
- name: Stop the firewall
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
- name: Start the firewall with salt-master service enabled
  ansible.builtin.systemd:
    name: firewalld
    state: started
- name: Ensure the Salt Master is installed
  ansible.builtin.yum:
    name: salt-master
    state: present
- name: Ensure data folders exists
  ansible.builtin.file:
    path: "/opt/{{ fld }}"
    state: directory
  loop:
    - salt
    - pillar
  loop_control:
    loop_var: fld
- name: Create the top.sls file
  ansible.builtin.copy:
    content: |
      base:
        'control01.jamesjonesconsulting.com':
          - cockpit
    dest: /opt/salt/top.sls
- name: Create the cockpit directory
  ansible.builtin.file:
    path: /opt/salt/cockpit
    state: directory
- name: Create cockpit init.sls file 
  ansible.builtin.copy:
    content: |
      cockpit:
        pkg:
          - installed
        service:
          - name: cockpit.socket
          - running
          - enable: true
        firewalld.present:
          - name: public
          - services
            - cockpit 
    dest: /opt/salt/cockpit/init.sls
# - name: Ensure the pilar base exists
#   ansible.builtin.file:
#     path: /etc/salt/pillar.d
#     state: directory
- name: Setup the Salt Master configs
  ansible.builtin.template:
    src: "templates/master.d/{{ cfg }}.conf.j2"
    dest: "/etc/salt/master.d/{{ cfg }}.conf"
  loop:
    - pillar
    - file
  loop_control:
    loop_var: cfg
- name: Ensure the master is restarted
  ansible.builtin.systemd:
    name: salt-master
    state: restarted
    enabled: true