---
- name: Gather facts from all servers
  ansible.builtin.setup:
  delegate_to: "{{ host }}"
  delegate_facts: true
  loop: "{{ groups[generate_hosts_group] }}"
  loop_control:
    loop_var: host
- name: Construct the state base list
  ansible.builtin.set_fact:
    top_base: "(top_base | default({}) | {host: states})"
  loop: "{{ groups[generate_hosts_group] }}"
  loop_control:
    loop_var: host
  

    #   base:
    #     'control01.jamesjonesconsulting.com':
    #       - cockpit
    # dest: /opt/salt/top.sls
